export const categories: string[] = [
  'business',
  'entertainment',
  'general',
  'health',
  'science',
  'sports',
  'technology',
];
export const countries = [
  {code: 'ae', flag: 'https://flagcdn.com/w320/ae.png'},
  {code: 'ar', flag: 'https://flagcdn.com/w320/ar.png'},
  {code: 'at', flag: 'https://flagcdn.com/w320/at.png'},
  {code: 'au', flag: 'https://flagcdn.com/w320/au.png'},
  {code: 'be', flag: 'https://flagcdn.com/w320/be.png'},
  {code: 'bg', flag: 'https://flagcdn.com/w320/bg.png'},
  {code: 'br', flag: 'https://flagcdn.com/w320/br.png'},
  {code: 'ca', flag: 'https://flagcdn.com/w320/ca.png'},
  {code: 'ch', flag: 'https://flagcdn.com/w320/ch.png'},
  {code: 'cn', flag: 'https://flagcdn.com/w320/cn.png'},
  {code: 'co', flag: 'https://flagcdn.com/w320/co.png'},
  {code: 'cu', flag: 'https://flagcdn.com/w320/cu.png'},
  {code: 'cz', flag: 'https://flagcdn.com/w320/cz.png'},
  {code: 'de', flag: 'https://flagcdn.com/w320/de.png'},
  {code: 'eg', flag: 'https://flagcdn.com/w320/eg.png'},
  {code: 'fr', flag: 'https://flagcdn.com/w320/fr.png'},
  {code: 'gb', flag: 'https://flagcdn.com/w320/gb.png'},
  {code: 'gr', flag: 'https://flagcdn.com/w320/gr.png'},
  {code: 'hk', flag: 'https://flagcdn.com/w320/hk.png'},
  {code: 'hu', flag: 'https://flagcdn.com/w320/hu.png'},
  {code: 'id', flag: 'https://flagcdn.com/w320/id.png'},
  {code: 'ie', flag: 'https://flagcdn.com/w320/ie.png'},
  {code: 'il', flag: 'https://flagcdn.com/w320/il.png'},
  {code: 'in', flag: 'https://flagcdn.com/w320/in.png'},
  {code: 'it', flag: 'https://flagcdn.com/w320/it.png'},
  {code: 'jp', flag: 'https://flagcdn.com/w320/jp.png'},
  {code: 'kr', flag: 'https://flagcdn.com/w320/kr.png'},
  {code: 'lt', flag: 'https://flagcdn.com/w320/lt.png'},
  {code: 'lv', flag: 'https://flagcdn.com/w320/lv.png'},
  {code: 'ma', flag: 'https://flagcdn.com/w320/ma.png'},
  {code: 'mx', flag: 'https://flagcdn.com/w320/mx.png'},
  {code: 'my', flag: 'https://flagcdn.com/w320/my.png'},
  {code: 'ng', flag: 'https://flagcdn.com/w320/ng.png'},
  {code: 'nl', flag: 'https://flagcdn.com/w320/nl.png'},
  {code: 'no', flag: 'https://flagcdn.com/w320/no.png'},
  {code: 'nz', flag: 'https://flagcdn.com/w320/nz.png'},
  {code: 'ph', flag: 'https://flagcdn.com/w320/ph.png'},
  {code: 'pl', flag: 'https://flagcdn.com/w320/pl.png'},
  {code: 'pt', flag: 'https://flagcdn.com/w320/pt.png'},
  {code: 'ro', flag: 'https://flagcdn.com/w320/ro.png'},
  {code: 'rs', flag: 'https://flagcdn.com/w320/rs.png'},
  {code: 'ru', flag: 'https://flagcdn.com/w320/ru.png'},
  {code: 'sa', flag: 'https://flagcdn.com/w320/sa.png'},
  {code: 'se', flag: 'https://flagcdn.com/w320/se.png'},
  {code: 'sg', flag: 'https://flagcdn.com/w320/sg.png'},
  {code: 'si', flag: 'https://flagcdn.com/w320/si.png'},
  {code: 'sk', flag: 'https://flagcdn.com/w320/sk.png'},
  {code: 'th', flag: 'https://flagcdn.com/w320/th.png'},
  {code: 'tr', flag: 'https://flagcdn.com/w320/tr.png'},
  {code: 'tw', flag: 'https://flagcdn.com/w320/tw.png'},
  {code: 'ua', flag: 'https://flagcdn.com/w320/ua.png'},
  {code: 'us', flag: 'https://flagcdn.com/w320/us.png'},
  {code: 've', flag: 'https://flagcdn.com/w320/ve.png'},
  {code: 'za', flag: 'https://flagcdn.com/w320/za.png'},
];
